// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMzK83pdobBOlpF1Ss7oaEivqcFYhzZ4Q',
    appId: '1:331315579834:web:672ba050ee229182b66b83',
    messagingSenderId: '331315579834',
    projectId: 'e-wallet-7d147',
    authDomain: 'e-wallet-7d147.firebaseapp.com',
    storageBucket: 'e-wallet-7d147.firebasestorage.app',
    measurementId: 'G-0NZ7YHH3T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqtCGT6KWvLOBWg8iBVfIegbH-lDsz5mc',
    appId: '1:331315579834:android:fae812119f0518b9b66b83',
    messagingSenderId: '331315579834',
    projectId: 'e-wallet-7d147',
    storageBucket: 'e-wallet-7d147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbRCQcuzAFvQFv5oOHKZOgpANqsrxMfk',
    appId: '1:331315579834:ios:91b9d52872fd3dd0b66b83',
    messagingSenderId: '331315579834',
    projectId: 'e-wallet-7d147',
    storageBucket: 'e-wallet-7d147.firebasestorage.app',
    iosBundleId: 'com.example.eWallet',
  );
}
